This commit was manufactured by cvs2svn to create tag 'installation-images-sl_8_2-3_30'.

diff --git a/data/demo/sbin/live-shutdown b/data/demo/sbin/live-shutdown
--- a/data/demo/sbin/live-shutdown
+++ b/data/demo/sbin/live-shutdown
@@ -1,9 +1,23 @@
 #! /bin/sh
 
-debug=
-
 PATH=$PATH:/S.u.S.E./bin:S.u.S.E./usr/bin
 cd /
+
+if [ -f /etc/liveeval.conf ] ; then
+  . /etc/liveeval.conf
+else
+  exit 1
+fi
+
+debug=
+nodisk=
+x=",$live,"
+[ "$x" != "${x/,debug,}" ] && debug=1
+
+partition=
+[ "$l_nodisk" ] && nodisk=1
+[ "$l_partition" ] && partition=/dev/$l_partition
+
 
 [ "$debug" ] && echo $LINENO && /bin/bash
 
@@ -20,43 +34,23 @@ fi
 
 LANG=$RC_LANG gettext -n -s "Saving LiveEval CD changes"
 
-if [ -f /etc/install.inf ]; then
-  eval `grep ': ' /etc/install.inf | sed -e 's/:  */="/' -e 's/$/"/' -e 's/^/export /'`
-fi
-
-if [ -f /etc/SuSElive ] ; then
-  . /etc/SuSElive
-else
-  exit 1
-fi
-
 [ "$debug" ] && echo $LINENO && /bin/bash
 
-if [ "$part" -a "$suseimg" ]; then
-  i=
-  [ "$dosdrive" ] && i="$dosdrive, "
+if [ ! "$nodisk" ]; then
   echo
-  printf "`LANG=$RC_LANG gettext 'Writing info to %s on %s (%s, %s MB)'`" "$suseimg" "$part" "$i$fstype" "$partsize"
+  printf "`LANG=$RC_LANG gettext 'Writing LiveEval config'`"
   echo
 
-  mount -n $part /mnt || error=21
+  error=
+  mount -n $partition /mnt || error=21
 
-  if [ "$error" = "" -a "$suseimg" ] ; then
-    if [ -f /etc/.SuSEfiles ] ; then
-      mount -n -oremount,rw /
-      rm -f /etc/.SuSErmlist
-      for i in `cat /etc/.SuSEfiles` ; do
-        if [ ! -e "$i" -a ! -L "$i" ] ; then
-          echo "$i" >>/etc/.SuSErmlist
-        fi
-      done
-      mount -n -oremount,ro /
-    fi
-    tar --exclude /dev/console -zclf /mnt/$suseimg / 2>/dev/null || error=1
+  if [ ! "$error" ] ; then
+    cd /
+    tar -zclf /mnt/$liveconfig . 2>/dev/null || error=1
   fi
 
   if [ "$error" ] ; then
-    printf "`LANG=$RC_LANG gettext 'An error occurred while writing %s.'`" "$suseimg"
+    printf "`LANG=$RC_LANG gettext 'An error occurred while writing %s.'`" "$liveconfig"
     echo
     LANG=$RC_LANG gettext -s "Sorry, your LiveEval CD changes might be lost. :-("
   fi
